#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#include "amd_shadow_callbacks.glsl"
#include "ThirdParty/FidelityFX/denoiser/ffx_denoiser_shadows_filter.h"
layout(local_size_x=8,local_size_y=8) in;
void main() {
    uvec2 p=gl_GlobalInvocationID.xy;
    if(ad.Stage==3u)DenoiserShadowsFilterPass0(gl_WorkGroupID.xy,gl_LocalInvocationID.xy,p);
    else if(ad.Stage==4u)DenoiserShadowsFilterPass1(gl_WorkGroupID.xy,gl_LocalInvocationID.xy,p);
    else DenoiserShadowsFilterPass2(gl_WorkGroupID.xy,gl_LocalInvocationID.xy,p);
}
