#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_KHR_shader_subgroup_quad : require
#include "amd_shadow_callbacks.glsl"
uint ffxWaveLaneCount() { return gl_SubgroupSize; }
bool ffxWaveAllTrue(bool value) { return subgroupAll(value); }
float ffxQuadReadX(float value) { return subgroupQuadSwapHorizontal(value); }
vec2 ffxQuadReadX(vec2 value) { return subgroupQuadSwapHorizontal(value); }
float ffxQuadReadY(float value) { return subgroupQuadSwapVertical(value); }
vec2 ffxQuadReadY(vec2 value) { return subgroupQuadSwapVertical(value); }
#include "ThirdParty/FidelityFX/denoiser/ffx_denoiser_shadows_tileclassification.h"
layout(local_size_x=8,local_size_y=8) in;
void main() { FFX_DNSR_Shadows_TileClassification(gl_LocalInvocationIndex,gl_WorkGroupID.xy); }
