#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#include "amd_reflection_half_callbacks.glsl"
#include "ThirdParty/FidelityFX/denoiser/ffx_denoiser_reflections_prefilter.h"
layout(local_size_x=8,local_size_y=8) in;
void main() { ArDispatchPixel=ivec2(ArTileOrigin(ArGroupIndex())+ffxRemapForWaveReduction(gl_LocalInvocationIndex)); Prefilter(gl_LocalInvocationIndex,ArGroupIndex(),ivec2(gl_LocalInvocationID.xy)); }

