#ifndef NJULF_DDGI_RECEIVER_FEEDBACK_SOURCE_ABI_GLSL
#define NJULF_DDGI_RECEIVER_FEEDBACK_SOURCE_ABI_GLSL

// Frozen producer-side subset of B1. It intentionally contains no push block
// so real receiver shaders can include it alongside their own pass constants.
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_ENDIAN_SENTINEL = 0x01020304u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CANDIDATE_WORDS = 12u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_ABI_VERSION = 0xb1012005u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_LAYOUT_REVISION = 0xb1012005u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_SURFACE_TILE_SCALE = 12u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_GLOBAL_HEADER_WORDS = 64u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_HEADER_WORDS = 16u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_RANGE_WORDS = 4u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_CONTROL_WORDS = 64u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_PRODUCER_COUNT = 7u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_KNOWN_PRODUCER_MASK =
    (1u << SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_PRODUCER_COUNT) - 1u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_READY = 1u << 0u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_SOURCE_GLOBAL_READY = 1u << 0u;

const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_ABI = 0u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_LAYOUT = 1u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_FRAME_COUNT = 2u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_FRAME_STRIDE = 3u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_HEADER_WORDS = 4u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_CONTROL_WORDS = 5u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_CANDIDATE_WORDS = 6u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_CAPACITY = 7u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_BYTES_LOW = 8u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_BYTES_HIGH = 9u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_FLAGS = 10u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_GLOBAL_ENDIAN = 11u;

const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_ABI = 0u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_LAYOUT = 1u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_GENERATION = 2u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_VIEWPORT = 3u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_FRAME_LOW = 4u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_FRAME_HIGH = 5u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_CAPACITY = 6u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_PRODUCER_COUNT = 7u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_SHARED_BASE = 8u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_SHARED_CAPACITY = 9u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_SHARED_COUNT = 10u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_OVERFLOW_MASK = 11u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_TOTAL_COUNT = 12u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_FLAGS = 13u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_ENDIAN = 14u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_REQUIRED_MASK = 15u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_COMPLETED_MASK = 44u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_SAMPLE_PERIOD = 45u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_SAMPLE_PHASE = 46u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_CONTROL_MAXIMUM_OWNERS = 47u;

const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_RANGE_BASE = 0u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_RANGE_CAPACITY = 1u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_RANGE_COUNT = 2u;
const uint SIMPLE_DDGI_RECEIVER_FEEDBACK_CAPTURE_RANGE_DROPPED = 3u;

#endif
