using Njulf.Core.Math;
using Njulf.Core.Scene;
using Njulf.Rendering.Core;
using Njulf.Rendering.Data;
using Njulf.Rendering.Memory;
using Njulf.Rendering.Resources;

namespace Njulf.Graphics;

/// <summary>
/// Creates resources on the renderer's existing device. Retrieve it with
/// <see cref="RendererGraphicsExtensions.GetGraphicsDevice"/> after host setup.
/// Operations require successful renderer initialization and the device thread.
/// The renderer owns this object and all underlying managers.
/// </summary>
internal sealed partial class VulkanGraphicsDevice : GraphicsDevice
{
    private readonly MeshManager _meshes;
    private readonly MaterialManager _materials;
    private readonly RendererLifetimeCoordinator _lifetime;
    private readonly int _deviceThreadId = Environment.CurrentManagedThreadId;

    internal VulkanContext Context { get; }
    internal BufferManager Buffers { get; }
    internal MeshManager Meshes => _meshes;
    internal MaterialManager Materials => _materials;
    /// <summary>Common settings, applied at production frame boundaries.</summary>
    private VulkanGraphicsSettingsController _settingsController = null!;
    public override VulkanGraphicsSettingsController Settings => _settingsController;
    internal void AttachSettings(RenderSettings settings) => _settingsController = new(settings, EnsureUsable)
    {
        ValidatePreset = preset => _materials.Diagnostics.PrimitiveProfileGpuBytes >
            Njulf.Rendering.Diagnostics.RenderBudgetEvaluator.ResolvePrimitiveProfileMemoryBudgetBytes(preset)
            ? "Existing primitive transport profiles exceed this preset's memory budget." : null
    };
    internal Vulkan.VulkanPassRegistry CustomPasses { get; private set; } = null!;
    private Func<GraphicsCapabilities> _capabilities = null!;
    internal bool RenderTargetsSupported { get; private set; }
    /// <summary>Reads current requests and latest actual execution; does not alter feature admission.</summary>
    public override GraphicsCapabilities Capabilities { get { EnsureUsable(); return _capabilities(); } }
    internal void AttachCapabilities(Func<GraphicsCapabilities> capture) => _capabilities = capture;
    internal bool QueryRenderTargetSupport() => RenderTargetsSupported = VulkanGraphicsCapabilities.SupportsRenderTargets(Context);
    internal void AttachCustomPasses(Njulf.Rendering.Pipeline.RenderGraph graph,
        SwapchainManager swapchain, Njulf.Rendering.Descriptors.BindlessHeap heap)
        => CustomPasses = new(this, graph, swapchain, heap);

    internal VulkanGraphicsDevice(VulkanContext context, BufferManager buffers,
        MeshManager meshes, MaterialManager materials, RendererLifetimeCoordinator lifetime)
    {
        Context = context;
        Buffers = buffers;
        _meshes = meshes;
        _materials = materials;
        _lifetime = lifetime;
        meshes.GraphicsDevice ??= this;
        materials.GraphicsDevice ??= this;
    }

    /// <summary>
    /// Creates indexed triangle geometry from positions in scene units. Indices
    /// are zero-based; normals and production meshlets are generated by the existing
    /// mesh builder. Input spans are consumed before this method returns.
    /// </summary>
    public override VulkanMesh CreateMesh(ReadOnlySpan<Vector3> positions, ReadOnlySpan<uint> indices)
    {
        EnsureUsable();
        var vertices = new System.Numerics.Vector3[positions.Length];
        for (int i = 0; i < positions.Length; i++)
            vertices[i] = new(positions[i].X, positions[i].Y, positions[i].Z);
        MeshHandle handle = _meshes.RegisterMesh(vertices, indices.ToArray());
        try { return new VulkanMesh(this, handle); }
        catch { DeferRelease(() => _meshes.ReleaseMesh(handle)); throw; }
    }

    /// <summary>
    /// Compiles an authored material with the existing material compiler and defaults.
    /// Use the texture-assignment overload for textured materials; callers keep
    /// ownership of their texture references.
    /// </summary>
    public override VulkanMaterial CreateMaterial(MaterialDefinition definition) => CreateMaterial(definition, ReadOnlySpan<MaterialTextureAssignment>.Empty);

    /// <summary>
    /// Creates an object with independent mesh/material references and local bounds.
    /// The caller owns the object until attaching it to a scene. Disposing the input
    /// wrappers does not invalidate the object. Both resources must belong to this device.
    /// </summary>
    public override RenderObject CreateRenderObject(IMesh mesh, IMaterial material)
    {
        ValidateMesh(mesh);
        ArgumentNullException.ThrowIfNull(material);
        ObjectDisposedException.ThrowIf(material.IsDisposed, material);
        if (material is not VulkanMaterial owned || !ReferenceEquals(owned.OwnerIdentity, Context))
            throw new ArgumentException("Material belongs to another graphics device.", nameof(material));
        return new RenderObject(mesh, material);
    }

    internal readonly GraphicsReleaseQueue Releases = new();
    internal void RetainMesh(MeshHandle handle) { EnsureUsable(); _meshes.RetainMesh(handle); }
    internal void RetainMaterial(MaterialHandle handle) { EnsureUsable(); _materials.RetainMaterial(handle); }
    internal string GetMaterialName(MaterialHandle handle) => _materials.GetMaterialDefinition(handle).Name;
    internal BoundingBox GetMeshBounds(MeshHandle handle)
    {
        var info = _meshes.GetMeshInfo(handle);
        return new(new(info.BoundingBoxMin.X, info.BoundingBoxMin.Y, info.BoundingBoxMin.Z),
            new(info.BoundingBoxMax.X, info.BoundingBoxMax.Y, info.BoundingBoxMax.Z));
    }
    internal void DeferRelease(Action release)
    {
        if (_lifetime.DisposalCompleted) return;
        _lifetime.ThrowIfDisposalStarted();
        EnsureDeviceThread();
        Releases.Enqueue(release, _lifetime.FrameInProgress || _lifetime.SubmissionFaulted);
    }
    internal void QueueRelease(Action release)
    {
        if (_lifetime.DisposalCompleted) return;
        EnsureReleaseAllowed();
        Releases.EnqueueRetirement(release, _lifetime.FrameInProgress || _lifetime.SubmissionFaulted);
    }
    internal MeshHandle ValidateMesh(IMesh mesh)
    {
        EnsureUsable();
        ArgumentNullException.ThrowIfNull(mesh);
        ObjectDisposedException.ThrowIf(mesh.IsDisposed, mesh);
        if (mesh is not VulkanMesh owned || !ReferenceEquals(owned.OwnerIdentity, Context))
            throw new ArgumentException("The mesh belongs to another graphics device.", nameof(mesh));
        return owned.Handle;
    }

    internal void EnsureUsable()
    {
        _lifetime.ThrowIfDisposalStarted();
        EnsureDeviceThread();
        if (!_lifetime.InitializationSucceeded)
            throw new InvalidOperationException("Initialize the renderer before using graphics resources.");
        _lifetime.ThrowIfSubmissionFaulted();
    }

    internal void EnsureReleaseAllowed()
    {
        _lifetime.ThrowIfDisposalStarted();
        EnsureDeviceThread();
    }

    private void EnsureDeviceThread()
    {
        if (Environment.CurrentManagedThreadId != _deviceThreadId)
            throw new InvalidOperationException("Graphics resource operations require the device thread.");
    }

    internal void ReleaseMesh(MeshHandle handle)
    {
        if (_lifetime.DisposalCompleted) return;
        _lifetime.ThrowIfDisposalStarted();
        EnsureDeviceThread();
        DeferRelease(() => _meshes.ReleaseMesh(handle));
    }

    internal void ReleaseMaterial(MaterialHandle handle)
    {
        if (_lifetime.DisposalCompleted) return;
        _lifetime.ThrowIfDisposalStarted();
        EnsureDeviceThread();
        DeferRelease(() => _materials.ReleaseMaterial(handle));
    }
}
