<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Njulf.Core\Njulf.Core.csproj" />
    <ProjectReference Include="..\Njulf.Graphics\Njulf.Graphics.csproj" />
    <ProjectReference Include="..\Njulf.Rendering\Njulf.Rendering.csproj" />
    <ProjectReference Include="..\Njulf.Assets\Njulf.Assets.csproj" />
    <ProjectReference Include="..\Njulf.Input\Njulf.Input.csproj" />
    <None Update="Assets\tetrahedron.gltf" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\Content\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\Effects\*.njeffect.json" CopyToOutputDirectory="PreserveNewest" />
    <NjulfEffectShader Include="Assets\Effects\*.frag;Assets\Effects\*.comp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Njulf.Framework\Njulf.Framework.csproj" />
  </ItemGroup>
  <Import Project="..\Njulf.ShaderBuild\Njulf.Effects.targets" />
</Project>
