using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using Njulf.Rendering.Core;
using Njulf.Rendering.Data;
using Njulf.Rendering.Descriptors;
using Njulf.Rendering.Diagnostics;
using Njulf.Rendering.Memory;
using Njulf.Rendering.Utilities;
using Silk.NET.Vulkan;

namespace Njulf.Rendering.Resources;

public readonly record struct SimpleDdgiLightTreeGraphResourceSnapshot(
    BufferHandle Node,
    BufferHandle Leaf,
    BufferHandle State,
    BufferHandle Scratch);

public readonly record struct SimpleDdgiLightTreeRuntimeDiagnostics(
    SimpleDdgiLocalLightSamplingMode RequestedMode,
    SimpleDdgiLocalLightSamplingMode EffectiveMode,
    bool Qualified,
    bool PublicationValid,
    DdgiLightTreeBuildAction Action,
    DdgiLightTreeRebuildReason RebuildReason,
    int LocalLightCount,
    int LeafCapacity,
    int NodeCount,
    int MaximumDepth,
    ulong LightBufferRevision,
    ulong TopologyRevision,
    ulong ContentRevision,
    uint PublicationGeneration,
    ulong PlannedBytes,
    ulong AllocatedBytes,
    ulong PeakAllocatedBytes,
    ulong RetiredBytes,
    ulong AllocationFailureCount,
    ulong BuildCount,
    ulong RefitCount,
    ulong ReuseCount,
    ulong EmptyBypassCount,
    ulong PublicationValidationFailureCount,
    ulong PublicationReadbackBytes,
    bool PublicationFeedbackPending,
    string FallbackReason)
{
    public static SimpleDdgiLightTreeRuntimeDiagnostics Disabled { get; } = new(
        SimpleDdgiLocalLightSamplingMode.Auto,
        SimpleDdgiLocalLightSamplingMode.Exact,
        false,
        false,
        DdgiLightTreeBuildAction.BypassEmpty,
        DdgiLightTreeRebuildReason.None,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        false,
        "disabled");
}

/// <summary>
/// Owns exact-capacity, double-banked GPU light-tree storage. The manager never
/// scans lights on the CPU; membership, bounds, Morton keys, and rebuild
/// validation are generated by the compute stages from the canonical light
/// buffer. Old capacity generations are retained until renderer teardown,
/// avoiding device-idle stalls and descriptor use-after-free.
/// </summary>
public sealed class SimpleDdgiLightTreeGpuResources : IDisposable
{
    private const ulong StateReadbackBytes = 64UL;
    public const ulong ScratchHeaderWords = 16;
    public const ulong ScratchRecordWords = 12;
    public const ulong ScratchIndirectWords = 16;

    private readonly VulkanContext _context;
    private readonly BufferManager _bufferManager;
    private readonly LightManager _lightManager;
    private readonly RenderSettings _settings;
    private readonly Action? _waitForDescriptorReaders;
    private readonly object _sync = new();
    private readonly List<RetiredBuffer> _retiredBuffers = new();
    private readonly BufferHandle[] _stateReadbackBuffers =
        new BufferHandle[RenderingConstants.FramesInFlight];
    private readonly bool[] _stateReadbackRecorded =
        new bool[RenderingConstants.FramesInFlight];
    private readonly PublicationExpectation[] _stateReadbackExpectations =
        new PublicationExpectation[RenderingConstants.FramesInFlight];

    private BindlessHeap? _bindlessHeap;
    private BufferHandle _nodeBuffer = BufferHandle.Invalid;
    private BufferHandle _leafBuffer = BufferHandle.Invalid;
    private BufferHandle _stateBuffer = BufferHandle.Invalid;
    private BufferHandle _scratchBuffer = BufferHandle.Invalid;
    private ulong _nodeBytes;
    private ulong _leafBytes;
    private ulong _stateBytes;
    private ulong _scratchBytes;
    private int _leafCapacity;
    private int _paddedLeafCount;
    private int _nodeCount;
    private int _maximumDepth;
    private bool _publishedValid;
    private bool _publicationConfirmed;
    private int _publishedBank;
    private ulong _publishedLightBufferRevision;
    private ulong _publishedTopologyRevision;
    private ulong _publishedContentRevision;
    private uint _publicationGeneration;
    private int _refitAge;
    private bool _stateNeedsInitialization;
    private DdgiLightTreeBuildAction _pendingAction;
    private DdgiLightTreeRebuildReason _pendingReason;
    private int _pendingTargetBank;
    private LightFrameSnapshot _pendingSnapshot;
    private ulong _buildCount;
    private ulong _refitCount;
    private ulong _reuseCount;
    private ulong _emptyBypassCount;
    private ulong _plannedBytes;
    private ulong _peakAllocatedBytes;
    private ulong _allocationFailureCount;
    private ulong _publicationValidationFailureCount;
    private bool _forceExactFallback;
    private bool _retryAfterPublicationValidationFailure;
    private bool _disposed;

    public SimpleDdgiLightTreeGpuResources(
        VulkanContext context,
        BufferManager bufferManager,
        LightManager lightManager,
        RenderSettings settings,
        Action? waitForDescriptorReaders = null)
    {
        _context = context ?? throw new ArgumentNullException(nameof(context));
        _bufferManager = bufferManager ?? throw new ArgumentNullException(nameof(bufferManager));
        _lightManager = lightManager ?? throw new ArgumentNullException(nameof(lightManager));
        _settings = settings ?? throw new ArgumentNullException(nameof(settings));
        _waitForDescriptorReaders = waitForDescriptorReaders;
        Diagnostics = SimpleDdgiLightTreeRuntimeDiagnostics.Disabled;
    }

    public SimpleDdgiLightTreeRuntimeDiagnostics Diagnostics { get; private set; }

    /// <summary>
    /// Sampling mode safe for the current frame. A failed capacity transaction
    /// is deliberately converted to the exact estimator; an older complete
    /// publication is retained for later frames but is never sampled against a
    /// newer canonical light snapshot.
    /// </summary>
    public SimpleDdgiLocalLightSamplingMode EffectiveSamplingMode
    {
        get
        {
            lock (_sync)
                return ResolveEffectiveSamplingMode();
        }
    }

    public bool HasPendingGpuWork
    {
        get
        {
            lock (_sync)
            {
                return _pendingAction is
                    DdgiLightTreeBuildAction.BuildInactive or
                    DdgiLightTreeBuildAction.RefitInactive or
                    DdgiLightTreeBuildAction.PublishEmpty;
            }
        }
    }

    public DdgiLightTreeBuildAction PendingAction
    {
        get
        {
            lock (_sync)
                return _pendingAction;
        }
    }

    public BufferHandle StateBuffer => _stateBuffer;

    /// <summary>
    /// Captures the exact allocations published through the four light-tree
    /// descriptors. Before tree capacity exists every descriptor deliberately
    /// aliases the canonical light buffer, so the render graph must track that
    /// same allocation rather than an invalid optional handle.
    /// </summary>
    public SimpleDdgiLightTreeGraphResourceSnapshot CaptureGraphResources()
    {
        lock (_sync)
        {
            BufferHandle alias = _lightManager.LightBuffer;
            return new SimpleDdgiLightTreeGraphResourceSnapshot(
                ResolveGraphBuffer(_nodeBuffer, alias),
                ResolveGraphBuffer(_leafBuffer, alias),
                ResolveGraphBuffer(_stateBuffer, alias),
                ResolveGraphBuffer(_scratchBuffer, alias));
        }
    }

    public bool StateNeedsInitialization
    {
        get
        {
            lock (_sync)
                return _stateNeedsInitialization;
        }
    }

    public Silk.NET.Vulkan.Buffer GetStateVkBuffer()
    {
        lock (_sync)
        {
            if (!_stateBuffer.IsValid)
                throw new InvalidOperationException("The DDGI light-tree state buffer is not allocated.");
            return _bufferManager.GetBuffer(_stateBuffer);
        }
    }

    /// <summary>
    /// Consumes the state copied by the previous use of this frame slot. The
    /// caller invokes this only after that slot's fence has completed.
    /// </summary>
    public unsafe void ReadCompletedFrame(int frameIndex)
    {
        ValidateFrameIndex(frameIndex);
        lock (_sync)
        {
            if (!_stateReadbackRecorded[frameIndex] ||
                !_stateReadbackBuffers[frameIndex].IsValid)
            {
                return;
            }

            BufferHandle readback = _stateReadbackBuffers[frameIndex];
            _bufferManager.InvalidateBuffer(readback, 0, StateReadbackBytes);
            GPUDdgiLightTreeState state =
                *(GPUDdgiLightTreeState*)_bufferManager.GetMappedPointer(readback);
            PublicationExpectation expected = _stateReadbackExpectations[frameIndex];
            _stateReadbackRecorded[frameIndex] = false;

            bool valid = ValidatePublication(state, expected);
            bool isCurrent = IsCurrentPublication(expected);
            if (valid)
            {
                if (isCurrent)
                {
                    _publicationConfirmed = true;
                    _retryAfterPublicationValidationFailure = false;
                }
            }
            else
            {
                _publicationValidationFailureCount++;
                if (isCurrent)
                {
                    _publishedValid = false;
                    _publicationConfirmed = false;
                    _retryAfterPublicationValidationFailure = true;
                    _pendingReason =
                        DdgiLightTreeRebuildReason.PublicationValidationFailed;
                    _forceExactFallback = true;
                }
            }

            UpdateDiagnostics(
                _settings.GlobalIllumination
                    .EffectiveSimpleDdgiManyLightSamplingEnabled,
                valid ? string.Empty : "gpu-publication-validation-failed");
        }
    }

    /// <summary>
    /// Copies the finalized 64-byte publication header to fence-owned host
    /// storage. This is a verification path only; trace still validates the
    /// same state directly on the GPU before sampling.
    /// </summary>
    public unsafe void RecordPublicationReadback(
        CommandBuffer commandBuffer,
        int frameIndex)
    {
        ValidateFrameIndex(frameIndex);
        lock (_sync)
        {
            if (!_stateBuffer.IsValid ||
                !_stateReadbackBuffers[frameIndex].IsValid ||
                _pendingAction is not (
                    DdgiLightTreeBuildAction.BuildInactive or
                    DdgiLightTreeBuildAction.RefitInactive))
            {
                return;
            }

            Silk.NET.Vulkan.Buffer source =
                _bufferManager.GetBuffer(_stateBuffer);
            Silk.NET.Vulkan.Buffer destination =
                _bufferManager.GetBuffer(_stateReadbackBuffers[frameIndex]);
            BufferMemoryBarrier2 beforeCopy = BarrierBuilder.BufferBarrier(
                source,
                PipelineStageFlags2.ComputeShaderBit,
                AccessFlags2.ShaderStorageWriteBit,
                PipelineStageFlags2.TransferBit,
                AccessFlags2.TransferReadBit,
                0,
                StateReadbackBytes);
            ExecuteBufferBarrier(commandBuffer, beforeCopy);

            BufferCopy copy = new()
            {
                SrcOffset = 0,
                DstOffset = 0,
                Size = StateReadbackBytes
            };
            _context.Api.CmdCopyBuffer(
                commandBuffer,
                source,
                destination,
                1,
                &copy);

            BufferMemoryBarrier2 afterCopy = BarrierBuilder.BufferBarrier(
                destination,
                PipelineStageFlags2.TransferBit,
                AccessFlags2.TransferWriteBit,
                PipelineStageFlags2.HostBit,
                AccessFlags2.HostReadBit,
                0,
                StateReadbackBytes);
            ExecuteBufferBarrier(commandBuffer, afterCopy);
            _stateReadbackExpectations[frameIndex] =
                PublicationExpectation.FromCurrent(this);
            _stateReadbackRecorded[frameIndex] = true;
            UpdateDiagnostics(
                _settings.GlobalIllumination
                    .EffectiveSimpleDdgiManyLightSamplingEnabled,
                Diagnostics.FallbackReason);
        }
    }

    public void Register(BindlessHeap bindlessHeap)
    {
        ArgumentNullException.ThrowIfNull(bindlessHeap);
        lock (_sync)
        {
            ThrowIfDisposed();
            _bindlessHeap = bindlessHeap;
            RegisterCurrentBuffers();
        }
    }

    public void Prepare(in LightFrameSnapshot snapshot)
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            GlobalIlluminationSettings gi = _settings.GlobalIllumination;
            bool qualified = gi.EffectiveSimpleDdgiManyLightSamplingEnabled;
            bool referenceUnauthorized =
                gi.SimpleDdgiLocalLightSamplingMode ==
                    SimpleDdgiLocalLightSamplingMode.LegacyTopKReference &&
                !gi.ContentDependentRollout.ValidationReferenceModesAuthorized;
            bool treeMode = gi.SimpleDdgiLocalLightSamplingMode is
                SimpleDdgiLocalLightSamplingMode.Auto or
                SimpleDdgiLocalLightSamplingMode.LightTree;
            bool requiresTree = qualified &&
                treeMode &&
                snapshot.LocalLightCount > gi.SimpleDdgiExactLocalLightThreshold;

            _pendingSnapshot = snapshot;
            _pendingReason = DdgiLightTreeRebuildReason.None;
            _plannedBytes = 0;
            _forceExactFallback = false;
            if (!requiresTree)
            {
                if (snapshot.LocalLightCount == 0)
                {
                    _emptyBypassCount++;
                    _pendingAction = _publishedValid
                        ? DdgiLightTreeBuildAction.PublishEmpty
                        : DdgiLightTreeBuildAction.BypassEmpty;
                    _pendingReason = DdgiLightTreeRebuildReason.EmptyLocalSet;
                }
                else
                {
                    _pendingAction = DdgiLightTreeBuildAction.ReusePublished;
                    _reuseCount++;
                }

                UpdateDiagnostics(
                    qualified,
                    fallback: referenceUnauthorized
                        ? "reference-mode-not-authorized"
                        : !qualified
                            ? "device-profile-not-qualified"
                            : !treeMode
                                ? "exact-or-reference-mode"
                                : "exact-small-set");
                return;
            }

            int requiredPaddedLeaves = checked((int)BitOperations.RoundUpToPowerOf2(
                checked((uint)Math.Max(snapshot.LocalLightCount, 1))));
            if (!TryEnsureCapacity(requiredPaddedLeaves, out string allocationFailure))
            {
                _allocationFailureCount++;
                _forceExactFallback = true;
                _pendingAction = DdgiLightTreeBuildAction.KeepPreviousComplete;
                _pendingReason = DdgiLightTreeRebuildReason.AllocationFailed;
                UpdateDiagnostics(qualified, allocationFailure);
                return;
            }

            DdgiLightTreeBuildAction action =
                SimpleDdgiLightTreePublicationPolicy.SelectAction(
                    snapshot.LocalLightCount,
                    snapshot.Revision,
                    snapshot.TopologyRevision,
                    snapshot.ContentRevision,
                    _publishedLightBufferRevision,
                    _publishedTopologyRevision,
                    _publishedContentRevision,
                    refitAge: _refitAge,
                    maximumRefitAge: gi.SimpleDdgiLightTreeMaximumRefitAge,
                    previousPublicationValid: _publishedValid);
            _pendingAction = action;
            _pendingTargetBank = 1 - _publishedBank;
            _pendingReason = action switch
            {
                DdgiLightTreeBuildAction.BuildInactive when
                    _retryAfterPublicationValidationFailure =>
                    DdgiLightTreeRebuildReason.PublicationValidationFailed,
                DdgiLightTreeBuildAction.BuildInactive when !_publishedValid =>
                    DdgiLightTreeRebuildReason.FirstPublication,
                DdgiLightTreeBuildAction.BuildInactive when
                    snapshot.TopologyRevision != _publishedTopologyRevision =>
                    DdgiLightTreeRebuildReason.LeafMembershipChanged,
                DdgiLightTreeBuildAction.BuildInactive =>
                    DdgiLightTreeRebuildReason.MaximumRefitAge,
                _ => DdgiLightTreeRebuildReason.None
            };
            if (action == DdgiLightTreeBuildAction.ReusePublished)
                _reuseCount++;
            UpdateDiagnostics(qualified, string.Empty);
        }
    }

    public GPUDdgiLightTreePushConstants BuildPushConstants()
    {
        lock (_sync)
        {
            ThrowIfDisposed();
            GlobalIlluminationSettings gi = _settings.GlobalIllumination;
            ulong revision = _pendingSnapshot.Revision;
            ulong topology = _pendingSnapshot.TopologyRevision;
            ulong content = _pendingSnapshot.ContentRevision;
            ulong recordOffset = ScratchHeaderWords;
            ulong sortedOffset = checked(
                recordOffset + (ulong)_paddedLeafCount * ScratchRecordWords);
            ulong indirectOffset = checked(sortedOffset + (ulong)_paddedLeafCount);
            return new GPUDdgiLightTreePushConstants
            {
                LightCount = checked((uint)Math.Max(_pendingSnapshot.Count, 0)),
                LeafCapacity = checked((uint)_paddedLeafCount),
                PaddedLeafCount = checked((uint)_paddedLeafCount),
                NodeCount = checked((uint)_nodeCount),
                TargetStorageIndex = checked((uint)_pendingTargetBank),
                PublishedStorageIndex = checked((uint)_publishedBank),
                BuildAction = (uint)_pendingAction,
                MaximumDepth = checked((uint)_maximumDepth),
                UniformMixtureProbability = gi.SimpleDdgiLightTreeUniformMixtureProbability,
                ExactLightThreshold = checked((uint)gi.SimpleDdgiExactLocalLightThreshold),
                NodeBankStrideWords = checked((uint)((ulong)_nodeCount * 16UL)),
                LeafBankStrideWords = checked((uint)((ulong)_paddedLeafCount * 8UL)),
                ScratchRecordOffsetWords = checked((uint)recordOffset),
                ScratchSortedIndexOffsetWords = checked((uint)sortedOffset),
                ScratchIndirectOffsetWords = checked((uint)indirectOffset),
                PublicationGeneration = NextGeneration(_publicationGeneration),
                LightBufferRevisionLow = (uint)revision,
                LightBufferRevisionHigh = (uint)(revision >> 32),
                TopologyRevisionLow = (uint)topology,
                TopologyRevisionHigh = (uint)(topology >> 32),
                ContentRevisionLow = (uint)content,
                ContentRevisionHigh = (uint)(content >> 32),
                Flags = 0,
                Reserved0 = 0
            };
        }
    }

    public void MarkStateInitialized()
    {
        lock (_sync)
            _stateNeedsInitialization = false;
    }

    /// <summary>Called after all stages have been recorded into the frame transaction.</summary>
    public void MarkRecorded()
    {
        lock (_sync)
        {
            if (_pendingAction == DdgiLightTreeBuildAction.PublishEmpty)
            {
                _publishedValid = false;
                _publicationConfirmed = false;
                _publishedLightBufferRevision = _pendingSnapshot.Revision;
                _publishedTopologyRevision = _pendingSnapshot.TopologyRevision;
                _publishedContentRevision = _pendingSnapshot.ContentRevision;
                _publicationGeneration = NextGeneration(_publicationGeneration);
                _refitAge = 0;
            }
            else if (_pendingAction is
                DdgiLightTreeBuildAction.BuildInactive or
                DdgiLightTreeBuildAction.RefitInactive)
            {
                _publishedValid = true;
                _publicationConfirmed = false;
                _publishedBank = _pendingTargetBank;
                _publishedLightBufferRevision = _pendingSnapshot.Revision;
                _publishedTopologyRevision = _pendingSnapshot.TopologyRevision;
                _publishedContentRevision = _pendingSnapshot.ContentRevision;
                _publicationGeneration = NextGeneration(_publicationGeneration);
                if (_pendingAction == DdgiLightTreeBuildAction.BuildInactive)
                {
                    _buildCount++;
                    _refitAge = 0;
                }
                else
                {
                    _refitCount++;
                    _refitAge = _refitAge == int.MaxValue
                        ? int.MaxValue
                        : _refitAge + 1;
                }
            }
            UpdateDiagnostics(
                _settings.GlobalIllumination.EffectiveSimpleDdgiManyLightSamplingEnabled,
                Diagnostics.FallbackReason);
        }
    }

    private bool TryEnsureCapacity(int paddedLeafCount, out string failure)
    {
        failure = string.Empty;
        int maximumPaddedLeafCount = checked((int)BitOperations.RoundUpToPowerOf2(
            checked((uint)LightManager.MaxLights)));
        if (paddedLeafCount > maximumPaddedLeafCount)
        {
            failure = "allocation-capacity-exceeds-canonical-light-buffer";
            return false;
        }

        int nodeCount;
        ulong nodeBytes;
        ulong leafBytes;
        const ulong stateBytes = 128UL;
        const ulong readbackBytes =
            StateReadbackBytes * RenderingConstants.FramesInFlight;
        ulong scratchBytes;
        try
        {
            nodeCount = checked(paddedLeafCount * 2 - 1);
            nodeBytes = checked((ulong)nodeCount * 64UL * 2UL);
            leafBytes = checked((ulong)paddedLeafCount * 32UL * 2UL);
            ulong scratchWords = checked(
                ScratchHeaderWords +
                (ulong)paddedLeafCount * ScratchRecordWords +
                (ulong)paddedLeafCount +
                ScratchIndirectWords);
            scratchBytes = checked(scratchWords * 4UL);
            _plannedBytes = checked(
                nodeBytes + leafBytes + stateBytes + scratchBytes +
                readbackBytes);
        }
        catch (OverflowException)
        {
            failure = "allocation-size-overflow";
            return false;
        }

        if (_nodeBuffer.IsValid && paddedLeafCount <= _paddedLeafCount)
            return true;

        BufferHandle node = BufferHandle.Invalid;
        BufferHandle leaf = BufferHandle.Invalid;
        BufferHandle state = BufferHandle.Invalid;
        BufferHandle scratch = BufferHandle.Invalid;
        BufferHandle[] readbacks =
            new BufferHandle[RenderingConstants.FramesInFlight];
        try
        {
            node = CreateBuffer(
                nodeBytes,
                BufferUsageFlags.StorageBufferBit |
                BufferUsageFlags.TransferDstBit,
                "SimpleDDGI.LightTree.Nodes");
            leaf = CreateBuffer(
                leafBytes,
                BufferUsageFlags.StorageBufferBit |
                BufferUsageFlags.TransferDstBit,
                "SimpleDDGI.LightTree.Leaves");
            state = CreateBuffer(
                stateBytes,
                BufferUsageFlags.StorageBufferBit |
                BufferUsageFlags.TransferDstBit |
                BufferUsageFlags.TransferSrcBit,
                "SimpleDDGI.LightTree.State");
            scratch = CreateBuffer(
                scratchBytes,
                BufferUsageFlags.StorageBufferBit |
                BufferUsageFlags.TransferDstBit |
                BufferUsageFlags.IndirectBufferBit,
                "SimpleDDGI.LightTree.Scratch");
            for (int frameIndex = 0;
                 frameIndex < readbacks.Length;
                 frameIndex++)
            {
                if (_stateReadbackBuffers[frameIndex].IsValid)
                    continue;
                readbacks[frameIndex] = _bufferManager.CreateBuffer(
                    StateReadbackBytes,
                    BufferUsageFlags.TransferDstBit,
                    Vma.MemoryUsage.AutoPreferHost,
                    Vma.AllocationCreateFlags.MappedBit |
                        Vma.AllocationCreateFlags.HostAccessRandomBit,
                    $"SimpleDDGI.LightTree.StateReadback.Frame{frameIndex}",
                    MemoryBudgetCategory.DiagnosticsAndDebug);
            }
            _waitForDescriptorReaders?.Invoke();
        }
        catch (Exception exception)
        {
            Destroy(node);
            Destroy(leaf);
            Destroy(state);
            Destroy(scratch);
            foreach (BufferHandle readback in readbacks)
                Destroy(readback);
            if (!IsRecoverableAllocationFailure(exception))
                throw;
            failure = $"allocation-failed-{exception.GetType().Name}";
            return false;
        }

        if (_nodeBuffer.IsValid)
        {
            Retire(_nodeBuffer, _nodeBytes);
            Retire(_leafBuffer, _leafBytes);
            Retire(_stateBuffer, _stateBytes);
            Retire(_scratchBuffer, _scratchBytes);
        }

        _nodeBuffer = node;
        _leafBuffer = leaf;
        _stateBuffer = state;
        _scratchBuffer = scratch;
        for (int frameIndex = 0;
             frameIndex < readbacks.Length;
             frameIndex++)
        {
            if (readbacks[frameIndex].IsValid)
                _stateReadbackBuffers[frameIndex] = readbacks[frameIndex];
        }
        _nodeBytes = nodeBytes;
        _leafBytes = leafBytes;
        _stateBytes = stateBytes;
        _scratchBytes = scratchBytes;
        _leafCapacity = paddedLeafCount;
        _paddedLeafCount = paddedLeafCount;
        _nodeCount = nodeCount;
        _maximumDepth = BitOperations.Log2(checked((uint)paddedLeafCount));
        _peakAllocatedBytes = Math.Max(
            _peakAllocatedBytes,
            checked(CurrentAllocatedBytes() + RetiredBytes()));
        _publishedValid = false;
        _publicationConfirmed = false;
        _publishedBank = 0;
        _refitAge = 0;
        _stateNeedsInitialization = true;
        RegisterCurrentBuffers();
        return true;
    }

    private BufferHandle CreateBuffer(
        ulong bytes,
        BufferUsageFlags usage,
        string debugName)
    {
        return _bufferManager.CreateDeviceBuffer(
            bytes,
            usage,
            true,
            MemoryBudgetCategory.GlobalIllumination,
            debugName);
    }

    private void RegisterCurrentBuffers()
    {
        if (_bindlessHeap == null)
            return;
        BufferHandle alias = _lightManager.LightBuffer;
        Register(BindlessIndex.SimpleDdgiLightTreeNodeBuffer, _nodeBuffer, _nodeBytes, alias);
        Register(BindlessIndex.SimpleDdgiLightTreeLeafBuffer, _leafBuffer, _leafBytes, alias);
        Register(BindlessIndex.SimpleDdgiLightTreeStateBuffer, _stateBuffer, _stateBytes, alias);
        Register(BindlessIndex.SimpleDdgiLightTreeScratchBuffer, _scratchBuffer, _scratchBytes, alias);

        // The foliage proxy manager owns its frame-slot descriptors. Do not
        // rewrite them during a later tree-capacity growth transaction.
        // Decal candidates are invocation-local today, but the reserved ABI
        // slot must still have a valid fallback descriptor.
        Register(BindlessIndex.DdgiDecalCandidateBuffer, BufferHandle.Invalid, 0, alias);
    }

    private void Register(int index, BufferHandle preferred, ulong bytes, BufferHandle alias)
    {
        BufferHandle handle = preferred.IsValid ? preferred : alias;
        ulong range = preferred.IsValid ? bytes : _lightManager.LightBufferAllocatedBytes;
        _bindlessHeap!.RegisterStorageBuffer(
            index,
            _bufferManager.GetBuffer(handle),
            0,
            Math.Max(16UL, range));
    }

    private static BufferHandle ResolveGraphBuffer(
        BufferHandle preferred,
        BufferHandle alias) => preferred.IsValid ? preferred : alias;

    private void Retire(BufferHandle handle, ulong bytes)
    {
        if (handle.IsValid)
            _retiredBuffers.Add(new RetiredBuffer(handle, bytes));
    }

    private void UpdateDiagnostics(bool qualified, string fallback)
    {
        ulong retiredBytes = RetiredBytes();
        ulong allocated = CurrentAllocatedBytes();
        Diagnostics = new SimpleDdgiLightTreeRuntimeDiagnostics(
            _settings.GlobalIllumination.SimpleDdgiLocalLightSamplingMode,
            ResolveEffectiveSamplingMode(),
            qualified,
            _publishedValid && _publicationConfirmed,
            _pendingAction,
            _pendingReason,
            _pendingSnapshot.LocalLightCount,
            _leafCapacity,
            _nodeCount,
            _maximumDepth,
            _pendingSnapshot.Revision,
            _pendingSnapshot.TopologyRevision,
            _pendingSnapshot.ContentRevision,
            _publicationGeneration,
            _plannedBytes,
            allocated,
            _peakAllocatedBytes,
            retiredBytes,
            _allocationFailureCount,
            _buildCount,
            _refitCount,
            _reuseCount,
            _emptyBypassCount,
            _publicationValidationFailureCount,
            StateReadbackAllocatedBytes(),
            HasPublicationFeedbackPending(),
            fallback);
    }

    private SimpleDdgiLocalLightSamplingMode ResolveEffectiveSamplingMode()
    {
        GlobalIlluminationSettings gi = _settings.GlobalIllumination;
        if (_forceExactFallback)
            return SimpleDdgiLocalLightSamplingMode.Exact;
        if (!gi.EffectiveSimpleDdgiManyLightSamplingEnabled)
            return SimpleDdgiLocalLightSamplingMode.LegacyTopKReference;
        if (_pendingSnapshot.LocalLightCount <= gi.SimpleDdgiExactLocalLightThreshold)
            return SimpleDdgiLocalLightSamplingMode.Exact;
        return gi.SimpleDdgiLocalLightSamplingMode;
    }

    private static bool IsRecoverableAllocationFailure(Exception exception) =>
        exception is VulkanException or OutOfMemoryException;

    public void Dispose()
    {
        lock (_sync)
        {
            if (_disposed)
                return;
            _disposed = true;
            Destroy(_nodeBuffer);
            Destroy(_leafBuffer);
            Destroy(_stateBuffer);
            Destroy(_scratchBuffer);
            foreach (BufferHandle readback in _stateReadbackBuffers)
                Destroy(readback);
            foreach (RetiredBuffer retired in _retiredBuffers)
                Destroy(retired.Handle);
            _retiredBuffers.Clear();
        }
    }

    private void Destroy(BufferHandle handle)
    {
        if (handle.IsValid)
            _bufferManager.DestroyBuffer(handle);
    }

    private void ThrowIfDisposed() => ObjectDisposedException.ThrowIf(_disposed, this);

    private unsafe void ExecuteBufferBarrier(
        CommandBuffer commandBuffer,
        BufferMemoryBarrier2 barrier)
    {
        var dependency = new DependencyInfo
        {
            SType = StructureType.DependencyInfo,
            BufferMemoryBarrierCount = 1,
            PBufferMemoryBarriers = &barrier
        };
        _context.Api.CmdPipelineBarrier2(commandBuffer, &dependency);
    }

    private static bool ValidatePublication(
        in GPUDdgiLightTreeState state,
        in PublicationExpectation expected)
    {
        uint checksum = GPUDdgiLightTreeState.ComputeValidationChecksum(
            expected.PublicationGeneration,
            expected.LocalLightCount,
            expected.NodeCount,
            expected.LightBufferRevision,
            expected.TopologyRevision,
            expected.ContentRevision);
        return (state.Flags & GPUDdgiLightTreeState.ValidFlag) != 0 &&
            state.RootNodeIndex == expected.RootNodeIndex &&
            state.NodeCount == expected.NodeCount &&
            state.LeafCount == expected.LocalLightCount &&
            state.MaximumDepth == expected.MaximumDepth &&
            state.ActiveStorageIndex == expected.ActiveStorageIndex &&
            state.PublicationGeneration == expected.PublicationGeneration &&
            Combine(state.LightBufferRevisionLow,
                state.LightBufferRevisionHigh) ==
                expected.LightBufferRevision &&
            Combine(state.TopologyRevisionLow, state.TopologyRevisionHigh) ==
                expected.TopologyRevision &&
            Combine(state.ContentRevisionLow, state.ContentRevisionHigh) ==
                expected.ContentRevision &&
            state.ValidationChecksum == checksum &&
            state.Reserved0 == expected.PaddedLeafCount;
    }

    private bool IsCurrentPublication(in PublicationExpectation expectation) =>
        _publishedValid &&
        _publicationGeneration == expectation.PublicationGeneration &&
        _publishedBank == expectation.ActiveStorageIndex &&
        _publishedLightBufferRevision == expectation.LightBufferRevision &&
        _publishedTopologyRevision == expectation.TopologyRevision &&
        _publishedContentRevision == expectation.ContentRevision;

    private bool HasPublicationFeedbackPending()
    {
        for (int index = 0; index < _stateReadbackRecorded.Length; index++)
        {
            if (_stateReadbackRecorded[index])
                return true;
        }
        return false;
    }

    private ulong StateReadbackAllocatedBytes()
    {
        ulong bytes = 0;
        foreach (BufferHandle handle in _stateReadbackBuffers)
        {
            if (handle.IsValid)
                bytes = checked(bytes + StateReadbackBytes);
        }
        return bytes;
    }

    private ulong CurrentAllocatedBytes() => checked(
        _nodeBytes + _leafBytes + _stateBytes + _scratchBytes +
        StateReadbackAllocatedBytes());

    private ulong RetiredBytes()
    {
        ulong bytes = 0;
        foreach (RetiredBuffer retired in _retiredBuffers)
            bytes = checked(bytes + retired.Bytes);
        return bytes;
    }

    private static ulong Combine(uint low, uint high) =>
        low | ((ulong)high << 32);

    private static void ValidateFrameIndex(int frameIndex)
    {
        if ((uint)frameIndex >= RenderingConstants.FramesInFlight)
            throw new ArgumentOutOfRangeException(nameof(frameIndex));
    }

    private static uint NextGeneration(uint generation) =>
        generation == uint.MaxValue ? 1u : generation + 1u;

    private readonly record struct RetiredBuffer(BufferHandle Handle, ulong Bytes);

    private readonly record struct PublicationExpectation(
        uint RootNodeIndex,
        uint NodeCount,
        uint LocalLightCount,
        uint MaximumDepth,
        int ActiveStorageIndex,
        uint PublicationGeneration,
        ulong LightBufferRevision,
        ulong TopologyRevision,
        ulong ContentRevision,
        uint PaddedLeafCount)
    {
        public static PublicationExpectation FromCurrent(
            SimpleDdgiLightTreeGpuResources resources) => new(
            checked((uint)(resources._publishedBank * resources._nodeCount)),
            checked((uint)resources._nodeCount),
            checked((uint)resources._pendingSnapshot.LocalLightCount),
            checked((uint)resources._maximumDepth),
            resources._publishedBank,
            resources._publicationGeneration,
            resources._publishedLightBufferRevision,
            resources._publishedTopologyRevision,
            resources._publishedContentRevision,
            checked((uint)resources._paddedLeafCount));
    }
}
